---
version: "3"
networks:
  proxy-subnet:
    external: false
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    hostname: caddy
    depends_on:
      - tailscale
    networks:
      - proxy-subnet
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
  tailscale:
    image: tailscale/tailscale:latest
    network_mode: host
    restart: unless-stopped
    hostname: campfire
    environment:
      - TS_AUTHKEY=${TS_AUTHHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/etc/tailscaled/serve.json
      - TS_ACCEPT_DNS=true
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/serve.json:/etc/tailscaled/serve.json
      - tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - net_raw
      - sys_module
  redis:
    image: redis
    restart: unless-stopped
    hostname: redis
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - ${PWD}/redis.conf:/etc/redis/redis.conf
      - redis-data:/var/lib/redis
  web:
    image: campfire:latest
    restart: unless-stopped
    command: bundle exec thrust bin/start-app
    environment:
      - TZ=America/New_York
      - FORK_PER_JOB=false
      - INTERVAL=0.1
      - PORT=9000
      - SKIP_TELEMETRY=true
      - RAILS_ENV=production
      - SECRET_KEY_BASE_DUMMY=1
    network_mode: service:tailscale
    depends_on:
      - caddy
      - tailscale
      - redis
volumes:
  tailscale-data:
    driver: local
  redis-data:
    driver: local
