version: "3"
services:
  tailscale:
    image: tailscale/tailscale:latest
    restart: unless-stopped
    hostname: homebridge
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container --accept-routes
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/etc/tailscaled/serve-config
      - TS_ACCEPT_DNS=true
      - TS_USERSPACE=false
    volumes:
      - tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - type: bind
        source: ${PWD}/serve.json
        target: /etc/tailscaled/serve-config
        read_only: true
        bind:
          create_host_path: true
    cap_add:
      - net_admin
      - net_raw
      - sys_module
  web:
    image: homebridge/homebridge:latest
    restart: unless-stopped
    network_mode: service:tailscale
    environment:
      - TZ=America/New_York
    volumes:
      - ${PWD}/data:/homebridge
    depends_on:
      - tailscale
volumes:
  tailscale-data:
    driver: local
