---
version: "3"
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    depends_on:
      - tailscale
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ${PWD}/Caddyfile:/etc/caddy/Caddyfile
  tailscale:
    image: tailscale/tailscale:latest
    restart: unless-stopped
    hostname: accweb
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ACCEPT_DNS=true
      - TS_USERSPACE=false
    volumes:
      - tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - net_raw
      - sys_module
  web:
    image: accweb/accweb:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "9600-9610:9600-9610/tcp"
      - "9600-9610:9600-9610/udp"
    volumes:
      - ${PWD}/data:/accweb
      - ${HOME}/Steam:/accserver
    environment:
      - ACCWEB_HOST=0.0.0.0:8080
      - ACCWEB_ENABLE_TLS=false
      - ACCWEB_ADMIN_PASSWORD=${ACCWEB_ADMIN_PASSWORD}
      - ACCWEB_MOD_PASSWORD=${ACCWEB_MOD_PASSWORD}
      - ACCWEB_RO_PASSWORD=${ACCWEB_RO_PASSWORD}
      - ACCWEB_LOGLEVEL=info
      - ACCWEB_CORS="*"
volumes:
  tailscale-data:
    driver: local
  steam-data:
    driver: local
